[package]
name = "graphql_lang_types"
version = "0.0.4"
edition = "2021"
license = "MIT"

[dependencies]
intern = { git = "https://github.com/facebook/relay.git", tag = "v16.2.0" }
common_lang_types = { path = "../common_lang_types" }
strum = { version="0.25.0", features=["derive"] }
