[package]
name = "string_key_newtype"
version = "0.0.4"
edition = "2021"
license = "MIT"

[dependencies]
intern = { git = "https://github.com/facebook/relay.git", rev = "e5839e889bce8f51b1bd121f7cec9fda348f1094" }
