[package]
name = "graphql_schema_parser"
version = "0.0.4"
edition = "2021"
license = "MIT"

[dependencies]
graphql-syntax = { git = "https://github.com/facebook/relay.git#f53a93272a1d756c60de795090fe70ca9532bb67" }
intern = { git = "https://github.com/facebook/relay.git", rev = "e5839e889bce8f51b1bd121f7cec9fda348f1094" }
graphql_lang_types = { path = "../graphql_lang_types" }
common_lang_types = { path = "../common_lang_types" }
logos = "0.12"
thiserror = "1.0.40"
